### ISSUE TITLE
Docker Compose and Ubuntu snap versions of ToroDB MySQL ?

### ISSUE THREAD

**Issue by xet7** [torodb/stampede#203]
Hi,
it seems that ToroDB MySQL version works, according to some screenshot I did see.

Can you add Docker Compose and Ubuntu snap versions of ToroDB MySQL ?

I would like to make ToroDB MySQL version of Wekan, there is already PostgreSQL version at:
https://github.com/wekan/wekan-postgresql

**Comment by teoincontatto** [comment]
Hi xet7,

Ubuntu snap version should be already working with MySQL. You have to pass `--backend mysql` to enable MySQL backend for ToroDB Stampede.

Doing the MySQL docker compose is a bit more complicated since it require a setup script for MySQL and the MySQL client installed in our base docker image. We are planning to move this functionality into Java to allow a straightforward method to setup the backend with his JDBC driver. For now I think the best bet would be setup MySQL user and database using available environment variables and modify the ToroDB Stampede container command with something like `bash -c "sleep 120 && entry-point"` with TORODB_SETUP=false (or it will try to setup postgresql).
