### ISSUE TITLE
How i can prevent torodb to create duplicate columns on the basis of the datatype of the values in that column. 

### ISSUE THREAD

**Issue by rajatsehgal2010** [torodb/stampede#226]
For ex- if we are having a column name "phone_number" with different datatype values, for ex- "823483292" and another is 8234923949  so it will create  two columns for phone_number_s and phone_number_n for different values.

I want to have single column for phone_number, how i can disable the duplicacy?

**Comment by teoincontatto** [comment]
Hi @rajatsehgal2010, the column duplicity depending on type can not be disabled. When we design ToroDB we decided that separating values of a same key by actual type was the correct way since that minimize storage usage and PostgreSQL store NULLs in a very compact way (each NULL occupy just a bit).

A good solution to your problem would be to create a view on the table that while reading merge columns with same prefix. For example:

```
CREATE VIEW <view name> AS
  SELECT coalesce(phone_number_s::text, phone_number_n::text) as phone_number
  FROM <table name>
```
